name: Run PowerShell Script

on:
  push:
    branches:
      - main



jobs:
  run_script:
    runs-on: windows-host
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v4
      
      - name: Run PowerShell script
        run: |
          & $env:ps2exe -inputFile ./rtfm.ps1 -outputFile rtfm.exe -requireadmin          
        
      - name: List files in the current directory
        run: ls

      - name: Commit and push changes
        run: |
          git fetch origin
          git config --local user.email "trwidick@gmail.com"
          git config --local user.name "Gitea Action"
          git add ./rtfm.exe
          git commit -m "Upload rtfm.exe"
          git push
          Remove-Item -R ./* 